karpenter:
  enabled: true
  version: 0.37.0
  values:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: usage
              operator: In
              values:
              - karpenter
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
    settings:
      clusterName: "batcave-dev"
      interruptionQueue: "Karpenter-bactave-dev"
