apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: {{ .Values.nodeClass.metadata.name | default "default" | quote }}
  annotations:
{{- range $key, $value := .Values.nodeClass.metadata.annotations }}
    {{ $key }}: "{{ $value }}"
{{- end }}
spec:
  amiFamily: {{ .Values.nodeClass.spec.amiFamily | default "AL2" | quote }}
  blockDeviceMappings:
{{- range .Values.nodeClass.spec.blockDeviceMappings }}
    - deviceName: {{ .deviceName | quote }}
      ebs:
        volumeType: {{ .ebs.volumeType | quote }}
        volumeSize: {{ .ebs.volumeSize | quote }}
        deleteOnTermination: {{ .ebs.deleteOnTermination | quote }}
{{- end }}
  role: "{{ .Values.nodeClass.spec.role }}"
  associatePublicIPAddress: {{ .Values.nodeClass.spec.associatePublicIPAddress | default false }}   
  subnetSelectorTerms:
    - tags:
        Name: "{{ .Values.nodeClass.spec.subnetTag }}"
  securityGroupSelectorTerms:
    - id: "{{ .Values.nodeClass.spec.securityGroupID }}"    
  tags:
{{- range $key, $value := .Values.nodeClass.spec.tags }}
    {{ $key }}: "{{ $value }}"
{{- end }}
  userData: |
    {{- if .Values.nodeClass.spec.userData }}
    {{ .Values.nodeClass.spec.userData | indent 4 }}
    {{- end }}
