apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:us-east-1:111594127594:secret:impl/db-creds-test-secret-driver-H6jEgV"
        jmesPath: 
            - path: db_username
            - path: db_password