{{- $this := .Values.karpenter }}
{{- $applicationName := "karpenter" }}
{{- $chartName := $applicationName }}
{{- $chartRepository := default $.Values.repo "public.ecr.aws/karpenter" }}
{{- $destinationNamespace := default $applicationName $this.namespace }}
{{- if $this.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "%s-%s" $.Values.project.name $applicationName }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ $destinationNamespace }}
    server: {{ $.Values.cluster.address }}
  project: {{ $.Values.project.name }}
  source:
    repoURL: {{ $chartRepository }}
    targetRevision: {{ $this.version }}
    chart: {{ $chartName }}
    helm:
      releaseName: {{ $applicationName }}
      {{- with $this.values }}
      values: |- {{- toYaml . | nindent 8 }}
        {{- end }}
  {{- with $this.syncPolicy }}
  syncPolicy:{{- toYaml $this.syncPolicy | nindent 4 }}
  {{- end }}
  {{- end -}}
