nodePool:
  metadata:
    name: "default-nodepool"
    annotations: {}
  spec:
    template:
      spec:
        requirements: []
        taints: []
        nodeClassRef:
          apiVersion: "karpenter.k8s.aws/v1beta1"
          kind: "EC2NodeClass"
          name: "default"
  consolidationPolicy: "WhenUnderutilized"
  expireAfter: "160h"
