apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ado-app-secret-secret-provider-class   # name of the SecretProviderClass
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "arn:aws:secretsmanager:us-east-1:111594127594:secret:impl/test-VoxfSW"
        jmesPath:
            - path: db_username                # Define the schema. The current values is using the example secret.
              objectAlias: db_username
            - path: db_password
              objectAlias: db_password
            - path: db_name
              objectAlias: db_name
            - path: env
              objectAlias: env
  secretObjects:                               # SecretObject defines the desired state of synced K8s secret objects
  - data:
    - key: db_username                         # data field to populate in the synced K8s secret objects
      objectName: db_username                  # name of the mounted content to sync. This could be the object name or the object alias
    - key: db_password
      objectName: db_password
    - key: db_name
      objectName: db_name
    - key: env
      objectName: env
    secretName:  ado-app-secret                # name of the Kubernetes Secret object
    type: Opaque