kind: Pod
apiVersion: v1
metadata:
  name: test-pod
spec:
  containers:
  - image: registry.k8s.io/e2e-test-images/busybox:1.29-4
    name: busybox
    imagePullPolicy: IfNotPresent
    command:
    - "/bin/sleep"
    - "10000"
    envFrom:
    - secretRef:
        name: ado-app-secret  # name of the Kubernetes Secret object
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"  # Can be adjusted as needed
      readOnly: true
  serviceAccountName: app-test-secret-store-sa  # name of the ServiceAccount
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "ado-app-secret-secret-provider-class"  # name of the SecretProviderClass
