apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: {{ .Values.nodeClass.metadata.name | quote }}
  annotations:
{{- range $key, $value := .Values.nodeClass.metadata.annotations }}
    {{ $key }}: "{{ $value }}"
{{- end }}
spec:
  amiFamily: {{ .Values.nodeClass.spec.amiFamily | default "AL2" | quote }}
  subnetSelectorTerms:
    - tags:
        Name: "{{ .Values.nodeClass.spec.subnetTag }}"
  securityGroupSelectorTerms:
    - id: "{{ .Values.nodeClass.spec.securityGroupID }}"
  instanceProfile: {{ .Values.nodeClass.spec.instanceProfile }}
  amiSelectorTerms:
    - id: {{ .Values.nodeClass.spec.amiSelectorId }}
  userData: |
    {{ .Values.nodeClass.spec.userData }}
  tags:
{{- range $key, $value := .Values.nodeClass.spec.tags }}
    {{ $key }}: "{{ $value }}"
{{- end }}
 
  blockDeviceMappings:
    - deviceName: {{ .Values.nodeClass.spec.deviceName | default "/dev/xvda" }}
      ebs:
        volumeSize: {{ .Values.nodeClass.spec.volumeSize | default "300G" }}
        volumeType: {{ .Values.nodeClass.spec.volumeType | default "gp3" }}
        deleteOnTermination: {{ .Values.nodeClass.spec.deleteOnTermination | default true }}
        encrypted: {{ .Values.nodeClass.spec.encrypted | default true }}
        kmsKeyId: {{ .Values.nodeClass.spec.kmsKeyId }}