apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: {{ .Values.nodeClass.metadata.name | default "default" | quote }}
  annotations:
{{- range $key, $value := .Values.nodeClass.metadata.annotations }}
    {{ $key }}: "{{ $value }}"
{{- end }}
spec:
  amiFamily: {{ .Values.nodeClass.spec.amiFamily | default "AL2" | quote }}
  {{- if eq .Values.nodeClass.spec.amiFamily "Custom" }}
  amiSelectorTerms:
    - id: {{ .Values.nodeClass.spec.amiID | quote }}
  {{- end }}
  blockDeviceMappings:
  {{- if .Values.nodeClass.spec.bottlerocket }}
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 8G
        volumeType: gp3
        deleteOnTermination: true
        encrypted: true
    - deviceName: /dev/xvdb
      ebs:
        volumeSize: 300G
        volumeType: gp3
        deleteOnTermination: true
        encrypted: true
  {{- else }}
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 300G
        volumeType: gp3
        deleteOnTermination: true
        encrypted: true
  {{- end }}
  instanceProfile: "{{ .Values.nodeClass.spec.instanceProfile }}"
  associatePublicIPAddress: {{ .Values.nodeClass.spec.associatePublicIPAddress | default false }}   
  subnetSelectorTerms:
    - tags:
        Name: "{{ .Values.nodeClass.spec.subnetTag }}"
  securityGroupSelectorTerms:
    - id: "{{ .Values.nodeClass.spec.securityGroupID }}"    
  tags:
{{- range $key, $value := .Values.nodeClass.spec.tags }}
    {{ $key }}: "{{ $value }}"
{{- end }}
  userData: |
    {{- if .Values.nodeClass.spec.userData }}
    {{ .Values.nodeClass.spec.userData | indent 4 }}
    {{- end }}
