name: "Release Notes Check"

on:
  pull_request:
    branches:
      - main

jobs:
  release-notes-check:
    name: 'Release Notes Check'

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
      repository-projects: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
         since_last_remote_commit: false

      - name: "Check for New Release Notes"
        run: |
          RN_FOUND=false
          for nf in ${{ steps.changed-files.outputs.added_files }}; do
            if [[ "$nf" == "releases/"*.md ]]; then
              RN_FOUND=true
            fi
          done
          if [[ "${RN_FOUND}" == "true" ]]; then
            echo 'Success, new release notes detected.'
          else
            echo 'ERROR: No new release notes detected.'
            echo 'Add new release notes using releases/template.md as an example.'
            exit 1
          fi
